### ISSUE TITLE
jira-toggl-sync error

### ISSUE THREAD

**Issue by abkumbar** [christianrondeau/jira-toggl-sync#4]
Hey Guys,

I'm trying to run the jira-toggl-sync command so I can track JIRA work log time using Toggl, but it seems to be giving me an error.

I cloned the repo, opened the command line in the directory where the repository is saved and ran jia-toggl-sync, but it's giving me a 'jira-toggl-sync' is not recognized as an internal or external command error. Does this tool work or has there been any updates? Any help here is appreciated.

Abhi.

![error1](https://cloud.githubusercontent.com/assets/8495466/15130206/9ce8d4e8-1614-11e6-9d3e-fd48d43df04a.JPG)

**Comment by christianrondeau** [comment]
Hi @abkumbar! `jira-toggl-sync` is only available in source code. You need to build it, using Visual Studio or MSBuild. Once built, you'll have the `jira-toggl-sync.exe` executable under `bin/Debug`. Instructions on how to build a Microsoft .NET solution with NuGet packages can be found online.

There is no intention at the moment to provide builds in this repository unless there is higher demand. Let us know if you have trouble :)
